// Generated by https://quicktype.io

export interface Pokelist {
  count: number;
  next?: string;
  previous?: null;
  results: PokeSmall[];
}

export interface PokeSmall {
  name: string;
  url: string;
  id: number;
  img: string;
}
